version: '3.8'

services:
  new-year-counter:
    build: .
    container_name: new-year-counter-app
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем код для горячей перезагрузки (опционально)
      - ./app:/app/app
    restart: unless-stopped
